### ISSUE TITLE
ModuleNotFoundError: No module named 'deeplearning'

### ISSUE THREAD

**Issue by wangxiaoyunNV** [facebookresearch/FBTT-Embedding#6]
Hi, 
I first installed the library, it works well, then run tt_embeddings_benchmark.py, but it gives me the following error. 
The environment is cuda 11 and pytorch 1.7
```
$ python3 tt_embeddings_benchmark.py 
Traceback (most recent call last):
  File "tt_embeddings_benchmark.py", line 13, in <module>
    from tt_embeddings_ops import TTEmbeddingBag
  File "/home/xiaoyunw/FBTT-Embedding/tt_embeddings_ops.py", line 13, in <module>
    import deeplearning.fbtt_embedding.tt_embeddings as tt_embeddings
ModuleNotFoundError: No module named 'deeplearning'
```

**Comment by bilgeacun** [comment]
Hi, the issue should be fixed with the above commit. Thanks for the notice!
